### ISSUE TITLE
Error in Connectome?

### ISSUE THREAD

**Issue by mattbaker** [Interintel/ConnectomeEngine#1]
@Interintel,

I noticed this in the GoPiGo version:

``` python
def ADAL():
        postsynaptic['ADAR'] += 1
        postsynaptic['ADAR'] += 1
        #...
```

https://github.com/Interintel/ConnectomeEngine/blob/master/GoPiGoConnectomev5.py#L31

Is that extra line for "ADAR" an accident?

**Comment by Interintel** [comment]
This is due to the connectome whereas many neurons connect to one another
through both synaptic and gap junction (chemical and electrical)
connections. When we translated to code, we treat both connections the same
so we didn't discriminate and thus two connections were added. As Gabe
indicated, it doesn't really matter because the results are the same.

Tim

**Comment by mattbaker** [comment]
Thanks for clearing it up! That makes sense. I'm learning all kinds of new stuff :)
